### Register
POST http://localhost:8000/auth/register
Content-Type: application/json

{
  "email": "test2@gmail.com",
  "password": "abc123456"
}

### Login
POST http://localhost:8000/auth/login
Content-Type: application/json

{
  "email": "test2@gmail.com",
  "password": "abc123456"
}

### Create a short link
POST http://localhost:8000/links
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2ZTIwMzg4OC03YzQ3LTRjYWUtOWRjZi0yYjQ3YjkzNDE1ZDQiLCJleHAiOjE3ODQ2NTI4MzZ9.0Utb4mUWyzwLviugP9XcIYsHvbA9ZKSheUQJwNb_NmY
Content-Type: application/json

{
  "original_url": "https://x.com/home"
}

### Get all of a user's links
GET http://localhost:8000/links
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJmMjUxNWFiYy1hNjcyLTRmNzAtYmE2NS00MjJjYjNiNzFhZjgiLCJleHAiOjE3ODQxODE2OTh9.KJqKUafOn_YMZxQx_5xEhUEpp2ov36P-iEfl-P90qCk
Content-Type: application/json

### Delete a short link (soft delete)
DELETE http://localhost:8000/links/46fc896b-1664-4152-9c1e-e6a3d17033a5
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIzODc2OTVmYi1mNGNmLTRmZjAtYjQ5NS0wM2IwNjg2YzYwYTQiLCJleHAiOjE3ODQxODIzNDd9.32B1Bqsz4rmkkIr5k6TomqDSCuJkC6G4_Ny9APR4Kps
Content-Type: application/json

### REDIRECT TEST
GET http://localhost:8000/typeshit
Content-Type: application/json
