"""add event_id to click_events table for idempotency

Revision ID: 4e448ad71a34
Revises: 9c373fea7a51
Create Date: 2026-07-19 18:57:23.618398

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e448ad71a34'
down_revision: Union[str, Sequence[str], None] = '9c373fea7a51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('click_events', sa.Column('event_id', sa.UUID(), nullable=False))
    op.create_unique_constraint("uq_click_events_event_id", 'click_events', ['event_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_click_events_event_id", 'click_events', type_='unique')
    op.drop_column('click_events', 'event_id')
    # ### end Alembic commands ###
