"""revise link_id index to include timestamp

Revision ID: 8a0fe3de6347
Revises: a9147a3b2e36
Create Date: 2026-07-14 19:27:20.062609

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a0fe3de6347'
down_revision: Union[str, Sequence[str], None] = 'a9147a3b2e36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_click_events_link_id'), table_name='click_events')
    op.create_index('ix_click_events_link_id_timestamp', 'click_events', ['link_id', 'timestamp'], unique=False)
    op.drop_constraint(op.f('click_events_link_id_fkey'), 'click_events', type_='foreignkey')
    op.create_foreign_key(None, 'click_events', 'links', ['link_id'], ['id'])
    op.add_column('links', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_links_deleted_at'), 'links', ['deleted_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_links_deleted_at'), table_name='links')
    op.drop_column('links', 'deleted_at')
    op.drop_constraint(None, 'click_events', type_='foreignkey')
    op.create_foreign_key(op.f('click_events_link_id_fkey'), 'click_events', 'links', ['link_id'], ['id'], ondelete='CASCADE')
    op.drop_index('ix_click_events_link_id_timestamp', table_name='click_events')
    op.create_index(op.f('ix_click_events_link_id'), 'click_events', ['link_id'], unique=False)
    # ### end Alembic commands ###
